/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

const puppeteer = require('puppeteer');
const fs = require('fs');

/**
 * Server-side PDF Generation using Puppeteer
 * This script demonstrates how to capture a dashboard URL and convert it to a professional PDF.
 */
async function generateServerSidePDF(url, outputPath) {
  console.log(`Launching browser to capture: ${url}`);
  
  const browser = await puppeteer.launch({
    headless: "new",
    args: ['--no-sandbox', '--disable-setuid-sandbox']
  });

  try {
    const page = await browser.newPage();
    
    // Set viewport to a standard desktop size
    await page.setViewport({ width: 1200, height: 1600 });

    // Navigate to the dashboard
    await page.goto(url, { waitUntil: 'networkidle0' });

    // Optional: Inject CSS to hide UI elements like buttons/search bars during print
    await page.addStyleTag({
      content: `
        header, .filter-bar, button, .no-print { display: none !important; }
        .print-only { display: block !important; }
        body { background: white !important; }
      `
    });

    console.log('Generating PDF...');

    // Generate PDF with professional settings
    await page.pdf({
      path: outputPath,
      format: 'A4',
      printBackground: true,
      margin: {
        top: '20mm',
        right: '10mm',
        bottom: '20mm',
        left: '10mm'
      },
      displayHeaderFooter: true,
      headerTemplate: `
        <div style="font-size: 10px; width: 100%; text-align: center; color: #6366f1; font-family: sans-serif;">
          CCM Template Security Audit - Confidential
        </div>
      `,
      footerTemplate: `
        <div style="font-size: 10px; width: 100%; display: flex; justify-content: space-between; padding: 0 20px; color: #94a3b8; font-family: sans-serif;">
          <span>Generated by Template Analytics Tool</span>
          <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
        </div>
      `
    });

    console.log(`PDF successfully saved to: ${outputPath}`);
  } catch (error) {
    console.error('Puppeteer Error:', error);
  } finally {
    await browser.close();
  }
}

// Example usage (uncomment to run in a Node environment with puppeteer installed)
// const dashboardUrl = 'http://localhost:3000';
// const output = './reports/audit_report.pdf';
// generateServerSidePDF(dashboardUrl, output);

module.exports = { generateServerSidePDF };
