name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - developer2
 

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build & Quality Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Replace tokens in JSON
        uses: cschleiden/replace-tokens@v1
        with:
          files: 'firebase-applet-config.json'
        env:
          # Match these exactly to the placeholders in your JSON (without the underscores)
          VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          VITE_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          VITE_FIREBASE_AUTH: ${{ secrets.FIREBASE_AUTH }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
          VITE_FIREBASE_MSG_ID: ${{ secrets.FIREBASE_MSG_ID }}
          VITE_FIREBASE_STORAGE_ID: ${{ secrets.FIREBASE_STORAGE_ID }}
          VITE_FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}

      - name: Install and Build
        run: npm install && npm run build
        
      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
